DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE IF NOT EXISTS EMPLOYEE(
EMP_NAME VARCHAR(10) NOT NULL,
EMP_NO VARCHAR(14) NOT NULL,
DEPT_CODE CHAR(2) NOT NULL,
EMAIL VARCHAR(13) NOT NULL,
SALARY BIGINT NOT NULL
);

INSERT INTO `EMPLOYEE` VALUES
('지용', '970313-1194917','D6','SGR_@NAVER.COM',3000000);


SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY

FROM EMPLOYEE

WHERE (DEPT_CODE='D9' OR DEPT_CODE='D6') 

AND SALARY >= 3000000 AND EMAIL LIKE '___ \_%' AND BONUS IS NOT NULL;

SELECT * FROM EMPLOYEE WHERE BONUS IS NULL AND MANAGER_ID IS NOT NULL;